name: Selenium Tests

on: push
  #schedule:
    # Runs every 30 minutes
    #- cron: '0,30 * * * *'
  #workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install distutils
      run: sudo apt-get update && sudo apt-get install -y python3-distutils

    - name: Install setuptools
      run: python -m pip install --upgrade setuptools

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Start Xvfb and run tests
      run: |
        # Start Xvfb
        export DISPLAY=:99
        Xvfb :99 -screen 0 1280x1024x24 &
        # Run your Selenium test script
        python main.py
